### ISSUE TITLE
Licencja

### ISSUE THREAD

**Issue by iwane-pl** [sq9atk/sr0wx#2]
Chciałem zapytać, na jakiej licencji udostępniony jest ten projekt? Jedyne, co można znaleźć w repozytorium, to licencja Apache oryginalnych plików sq6jnx.

**Comment by sq9atk** [comment]
Apache 2.0

**Comment by sq9atk** [comment]
Jeśli chcesz rozwijać to oczywiście możesz. Z tego co wiem to chłopaki z MOA chcą to przepisać na py3. Michał JNX też nie ma nic przeciwko.

**Comment by iwane-pl** [comment]
Dzięki za odpowiedź.

W części mogę pomóc. Na dziś pewnie nie wyrobię się z kodowaniem (niestety), ale jakby trzeba było przejrzeć Pull Requesta albo inny kawał kodu, jestem otwarty.
